### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by kpapadatos** [monai/node-imagesearch#1]
`npm install imagesearch` does not build on Windows 8.
![image](https://cloud.githubusercontent.com/assets/3382344/7862191/f9e2d03c-055c-11e5-998f-8b0c4fc86cf3.png)

**Comment by monai** [comment]
It doesn't build because Node.js v0.12 comes with upgraded v8 which is far, far away from the one bundled with v0.10 and has drastically changed API for native bindings. As far as I remember, it does build on v0.10 on Windows.

I have no intention to upgrade this module to work with v0.12. If you're interested, rational upgrade path would be to rewrite native code on [nan](https://www.npmjs.com/package/nan).
