### ISSUE TITLE
Pure Javascript

### ISSUE THREAD

**Issue by ghafran** [monai/node-imagesearch#3]
Anyway you can make this a pure javascript library? 

Of course this would not be as performant, however it would work across all platforms.

Current having issues with build process on mac and linux with npm install.

**Comment by monai** [comment]
The core issue is that native bindings use v8 API directly and the API backwards compatibility was broken few times since Node.js v0.12 when i wrote this module. Reasonable solution would be to rewrite Node.js and v8 API calls to [nan](/nodejs/nan) but I'm not interested in this project anymore and won't do that, however I would accept merge request.

First version of an algorithm I implemented in pure JS but it was so slow that almost unusable. Since v8 doesn't support yet (and especially at the time I wrote this module) [vectorization](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD), an external library is needed.
